version: '3'

services:
  web:
    build:
      context: ./
      dockerfile: test.dockerfile
    ports:
      - 5000:5000
    volumes:
      - .:/app
    restart: unless-stopped
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      FLASK_DEBUG: 1
      SECRET_KEY: secret
      DATABASETYPE: SQLITE
      APP_SETTINGS: common.base.TestingConfig
      TESTING: True